name: concurrecy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true           # Cancel older runs on same branch

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10              # Job timeout
    steps:
      - name: ⏱️ Step with Timeout
        timeout-minutes: 2           # Step timeout
        run: |
          echo "This step must complete in 2 minutes"
          sleep 30
          echo "Completed within time!"
